//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EffectToolApplication.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_EffectToolApplicationTYPE   130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_EMITTER_SETTER              310
#define IDD_EMITTERLIST_VIEW            312
#define IDD_SHADER                      316
#define IDD_DIALOG2                     324
#define IDD_DIALOG1                     326
#define IDD_TEXTURE                     328
#define IDC_TEX_LIST                    1000
#define IDC_BROWSE_TEXFILE              1001
#define IDC_TEX_THUMBNAIL               1002
#define IDC_EMITTER_X                   1008
#define IDC_EMITTER_Y                   1009
#define IDC_EMITTER_Z                   1010
#define BUTTON_GEN_EMITTER              1011
#define ID_DELETE_EMITTER               1012
#define IDC_EMITTER_LIST                1014
#define IDC_CHECK_DB_WRITE              1015
#define IDC_CHECK_DB_CMP                1016
#define IDC_CHECK_ALPHA_TEST            1017
#define IDC_CHECK_ALPHA_BLEND           1018
#define IDC_CHECK_WIREFRAME             1019
#define IDC_RANDOMCOLOR                 1020
#define IDC_NOCOLOR                     1021
#define IDC_LIFETIME_MIN                1023
#define IDC_LIFETIME_MAX                1025
#define IDC_POS_MIN_X                   1029
#define IDC_POS_MIN_Y                   1030
#define IDC_POS_MIN_Z                   1031
#define IDC_POS_MAX_X                   1032
#define IDC_POS_MAX_Y                   1033
#define IDCANCEL                        1033
#define IDC_POS_MAX_Z                   1034
#define IDC_POS_MAX_Y2                  1034
#define IDC_UV_ROWS                     1034
#define IDC_SIZE_MIN_X                  1035
#define IDC_POS_MAX_Z2                  1035
#define IDC_UV_COLS                     1035
#define IDC_SIZE_MIN_Y                  1036
#define IDC_SIZE_MIN_X2                 1036
#define IDC_RADIO2                      1036
#define IDC_SIZE_MAX_X                  1037
#define IDC_SIZE_MIN_Y2                 1037
#define IDC_SINGLE_UV                   1037
#define IDC_SIZE_MAX_Y                  1038
#define IDC_SIZE_MAX_X2                 1038
#define IDC_SINGLE                      1038
#define IDC_EMITTER_INIT_NUM            1039
#define IDC_BUTTON1                     1039
#define IDC_EMITTER_EMIT_CYCLE          1040
#define IDC_EDIT1                       1040
#define IDC_SPAWNRATE                   1040
#define IDC_EMITTER_NAME                1041
#define IDC_CHECK1                      1041
#define IDC_DUALSOURCE                  1041
#define IDC_VEL_MIN_X                   1042
#define IDC_SIZE_MAX_Y2                 1042
#define IDC_VEL_MIN_Y                   1043
#define IDC_VEL_MIN_X2                  1043
#define IDC_VEL_MIN_Z                   1044
#define IDC_VEL_MIN_Y2                  1044
#define IDC_VEL_MAX_X                   1045
#define IDC_VEL_MIN_Z2                  1045
#define IDC_VEL_MAX_Y                   1046
#define IDC_VEL_MAX_X2                  1046
#define IDC_VEL_MAX_Z                   1047
#define IDC_VEL_MAX_Y2                  1047
#define IDC_VEL_MAX_Z2                  1048

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        330
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1042
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
